package util

import "github.com/tushariitr-19/immigration-mcp/models"

var ImmigrationTerms = map[string]models.ImmigrationTerm{
	"priority date": {
		Term:         "Priority Date",
		Simple:       "The date USCIS received your immigrant visa petition — it determines your place in line for a green card",
		Detail:       "For employment-based green cards, your priority date is established when USCIS receives your I-140 petition or when DOL certifies your PERM labor certification. It determines your place in the queue for a visa number. You can only file I-485 when your priority date becomes current according to the Visa Bulletin.",
		RelatedTerms: []string{"Visa Bulletin", "Final Action Date", "I-140", "PERM", "I-485"},
		Forms:        []string{"I-140", "I-485"},
		Source:       "https://travel.state.gov/content/travel/en/legal/visa-law0/visa-bulletin.html",
	},
	"final action date": {
		Term:         "Final Action Date",
		Simple:       "The cutoff date in the Visa Bulletin — your priority date must be before this date to file I-485",
		Detail:       "The Final Action Date (Chart A) in the Visa Bulletin is the date that determines when you can complete your green card process. If your priority date is earlier than this date, USCIS can approve your I-485. This is different from the Date for Filing which only determines when you can submit the application.",
		RelatedTerms: []string{"Priority Date", "Date for Filing", "Visa Bulletin", "I-485"},
		Forms:        []string{"I-485"},
		Source:       "https://travel.state.gov/content/travel/en/legal/visa-law0/visa-bulletin.html",
	},
	"date for filing": {
		Term:         "Date for Filing",
		Simple:       "An earlier cutoff date that allows you to submit I-485 even before your priority date is fully current",
		Detail:       "The Date for Filing (Chart B) in the Visa Bulletin allows applicants to file I-485 earlier than the Final Action Date. USCIS announces each month whether Chart A or Chart B applies. Filing early lets you get work authorization (EAD) and travel document (AP) while waiting for your priority date to become fully current.",
		RelatedTerms: []string{"Final Action Date", "Priority Date", "Visa Bulletin", "EAD", "Advance Parole"},
		Forms:        []string{"I-485", "I-765", "I-131"},
		Source:       "https://travel.state.gov/content/travel/en/legal/visa-law0/visa-bulletin.html",
	},
	"adjustment of status": {
		Term:         "Adjustment of Status",
		Simple:       "The process of getting a green card while staying inside the United States",
		Detail:       "Adjustment of Status (AOS) allows eligible applicants to become lawful permanent residents without leaving the US. You file Form I-485 with USCIS. The alternative is Consular Processing where you apply through a US embassy abroad. AOS requires your priority date to be current and you must be physically present in the US.",
		RelatedTerms: []string{"I-485", "Consular Processing", "Priority Date", "EAD", "Advance Parole"},
		Forms:        []string{"I-485", "I-765", "I-131", "I-693"},
		Source:       "https://www.uscis.gov/green-card/green-card-processes-and-procedures/adjustment-of-status",
	},
	"consular processing": {
		Term:         "Consular Processing",
		Simple:       "Getting your green card through a US embassy or consulate abroad instead of inside the US",
		Detail:       "Consular Processing is the alternative to Adjustment of Status. After I-140 approval and a visa number becoming available, you apply at a US embassy in your home country. You receive an immigrant visa, travel to the US, and become a green card holder upon entry. This is required if you are outside the US or ineligible for AOS.",
		RelatedTerms: []string{"Adjustment of Status", "I-140", "Priority Date", "NVC"},
		Forms:        []string{"I-140", "DS-260"},
		Source:       "https://www.uscis.gov/green-card/green-card-processes-and-procedures/consular-processing",
	},
	"perm": {
		Term:         "PERM Labor Certification",
		Simple:       "A Department of Labor process your employer must complete before sponsoring you for a green card",
		Detail:       "PERM (Program Electronic Review Management) is the first step in most employment-based green card processes. Your employer must prove to the Department of Labor that there are no qualified US workers available for the position. This involves posting the job, conducting recruitment, and filing Form 9089. PERM approval establishes your priority date.",
		RelatedTerms: []string{"Priority Date", "I-140", "EB2", "EB3", "DOL"},
		Forms:        []string{"ETA-9089"},
		Source:       "https://www.dol.gov/agencies/eta/foreign-labor/programs/permanent",
	},
	"i-140": {
		Term:         "Form I-140",
		Simple:       "The immigrant petition your employer files to start your green card process",
		Detail:       "Form I-140 (Immigrant Petition for Alien Workers) is filed by your employer after PERM approval (for EB2/EB3) or directly for EB1. It establishes your eligibility for the green card category. Once approved, it locks in your priority date permanently — even if you change employers. I-140 approval is separate from I-485 filing.",
		RelatedTerms: []string{"PERM", "Priority Date", "I-485", "EB1", "EB2", "EB3", "AC21"},
		Forms:        []string{"I-140"},
		Source:       "https://www.uscis.gov/i-140",
	},
	"i-485": {
		Term:         "Form I-485",
		Simple:       "The application to get your green card while inside the United States",
		Detail:       "Form I-485 (Application to Register Permanent Residence) is the final step in the Adjustment of Status process. You can file it when your priority date is current per the Visa Bulletin. Filing I-485 concurrently allows you to also file for EAD (work permit) and Advance Parole (travel document). Processing can take 1-3 years.",
		RelatedTerms: []string{"Adjustment of Status", "Priority Date", "EAD", "Advance Parole", "I-140"},
		Forms:        []string{"I-485", "I-765", "I-131", "I-693", "I-864"},
		Source:       "https://www.uscis.gov/i-485",
	},
	"ead": {
		Term:         "EAD (Employment Authorization Document)",
		Simple:       "A work permit that allows you to work for any employer in the US",
		Detail:       "The Employment Authorization Document (EAD), also called a work permit, is issued on Form I-766. When you file I-485, you can simultaneously file for an EAD which allows you to work for any employer — not just your green card sponsor. This is important because it gives you flexibility while your green card is pending. EADs are typically valid for 1-2 years and must be renewed.",
		RelatedTerms: []string{"I-765", "Advance Parole", "I-485", "H4 EAD", "OPT"},
		Forms:        []string{"I-765"},
		Source:       "https://www.uscis.gov/i-765",
	},
	"advance parole": {
		Term:         "Advance Parole",
		Simple:       "A travel document that lets you leave and re-enter the US while your green card is pending",
		Detail:       "Advance Parole (AP) is a travel document issued on Form I-131 that allows you to travel internationally and return to the US while your I-485 is pending. Without it, leaving the US while I-485 is pending is considered abandonment of your application. H1B holders can travel on their H1B visa instead, but having AP provides a safety net.",
		RelatedTerms: []string{"I-131", "I-485", "EAD", "Adjustment of Status"},
		Forms:        []string{"I-131"},
		Source:       "https://www.uscis.gov/i-131",
	},
	"h1b": {
		Term:         "H1B Visa",
		Simple:       "A work visa for specialty occupation workers — the most common visa for tech workers",
		Detail:       "The H1B visa allows US employers to employ foreign workers in specialty occupations requiring at least a bachelor's degree or equivalent. It is subject to an annual cap of 65,000 visas plus 20,000 for US master's degree holders. H1B is a dual intent visa meaning you can apply for a green card while on H1B. Valid for 3 years, extendable to 6 years, and beyond with a pending I-140.",
		RelatedTerms: []string{"LCA", "I-129", "H1B Cap", "H4", "AC21", "Specialty Occupation", "Prevailing Wage"},
		Forms:        []string{"I-129", "I-797"},
		Source:       "https://www.uscis.gov/working-in-the-united-states/h-1b-specialty-occupations",
	},
	"h4": {
		Term:         "H4 Visa",
		Simple:       "A dependent visa for spouses and children of H1B visa holders",
		Detail:       "The H4 visa is issued to immediate family members (spouse and unmarried children under 21) of H1B visa holders. H4 holders cannot work unless they qualify for H4 EAD. H4 status is tied to the H1B holder's status — if the H1B holder loses status, the H4 holder also loses status.",
		RelatedTerms: []string{"H1B", "H4 EAD", "I-539"},
		Forms:        []string{"I-539"},
		Source:       "https://www.uscis.gov/working-in-the-united-states/h-4-nonimmigrant",
	},
	"h4 ead": {
		Term:         "H4 EAD",
		Simple:       "Work authorization for H4 visa holders whose spouse has an approved I-140",
		Detail:       "H4 EAD allows H4 visa holders to work in the US if their H1B spouse has an approved I-140 petition. This was introduced in 2015 and has been subject to legal challenges. H4 EAD holders can work for any employer. It must be renewed with the H4 visa and is tied to the H1B holder's I-140 remaining approved.",
		RelatedTerms: []string{"H4", "H1B", "I-140", "EAD", "I-765"},
		Forms:        []string{"I-765"},
		Source:       "https://www.uscis.gov/working-in-the-united-states/h-4-nonimmigrant",
	},
	"ac21": {
		Term:         "AC21 / H1B Portability",
		Simple:       "A law that lets you change employers without restarting your green card process",
		Detail:       "The American Competitiveness in the 21st Century Act (AC21) provides two key protections: (1) H1B Portability — you can change employers as soon as a new H1B petition is filed, without waiting for approval; (2) I-485 Portability — if your I-485 has been pending 180+ days and your I-140 is approved, you can change to a same or similar job without losing your place in line.",
		RelatedTerms: []string{"H1B", "I-140", "I-485", "180-Day Rule", "Same or Similar"},
		Forms:        []string{"I-485", "I-129"},
		Source:       "https://www.uscis.gov/policy-manual/volume-7-part-d-chapter-9",
	},
	"180-day rule": {
		Term:         "180-Day Portability Rule",
		Simple:       "After your I-485 has been pending 180 days, you can change to a similar job without restarting your green card",
		Detail:       "Under AC21 Section 204(j), if your I-485 has been pending for at least 180 days and your I-140 is approved, you can change employers or job positions as long as the new job is in the same or similar occupational classification. You must notify USCIS of the change. This rule gives green card applicants significant job flexibility.",
		RelatedTerms: []string{"AC21", "I-485", "I-140", "Same or Similar"},
		Forms:        []string{"I-485"},
		Source:       "https://www.uscis.gov/policy-manual/volume-7-part-d-chapter-9",
	},
	"eb1": {
		Term:         "EB1 (First Preference Employment-Based)",
		Simple:       "The fastest green card category for priority workers — no PERM required",
		Detail:       "EB1 is the first preference employment-based green card category with three subcategories: EB1A (Extraordinary Ability — self petition, no employer needed), EB1B (Outstanding Professors and Researchers — employer required), and EB1C (Multinational Managers and Executives). No PERM labor certification required. Priority dates are typically current for most countries except India and China.",
		RelatedTerms: []string{"EB1A", "EB1B", "EB1C", "I-140", "Priority Date", "PERM"},
		Forms:        []string{"I-140"},
		Source:       "https://www.uscis.gov/green-card/green-card-eligibility/green-card-for-employment-based-immigrants",
	},
	"eb1a": {
		Term:         "EB1A (Extraordinary Ability)",
		Simple:       "A self-petition green card for people with extraordinary ability in their field",
		Detail:       "EB1A is for individuals with extraordinary ability in sciences, arts, education, business, or athletics. You must meet at least 3 of 10 criteria including awards, publications, judging others' work, high salary, etc. The key advantage is you can self-petition — no employer sponsorship needed. No PERM required. Strong evidence of sustained national or international acclaim is essential.",
		RelatedTerms: []string{"EB1", "I-140", "National Interest Waiver", "EB2 NIW"},
		Forms:        []string{"I-140"},
		Source:       "https://www.uscis.gov/green-card/green-card-eligibility/green-card-for-employment-based-immigrants",
	},
	"eb2": {
		Term:         "EB2 (Second Preference Employment-Based)",
		Simple:       "A green card category for professionals with advanced degrees or exceptional ability",
		Detail:       "EB2 is for members of professions holding advanced degrees (master's or higher, or bachelor's plus 5 years progressive experience) or those with exceptional ability in sciences, arts, or business. Typically requires PERM and employer sponsorship, unless filing under National Interest Waiver (NIW). India and China face significant backlogs in this category.",
		RelatedTerms: []string{"PERM", "I-140", "EB2 NIW", "Priority Date", "EB3"},
		Forms:        []string{"I-140", "ETA-9089"},
		Source:       "https://www.uscis.gov/green-card/green-card-eligibility/green-card-for-employment-based-immigrants",
	},
	"eb2 niw": {
		Term:         "EB2 NIW (National Interest Waiver)",
		Simple:       "A self-petition green card for EB2 applicants whose work benefits the United States",
		Detail:       "The National Interest Waiver allows EB2 applicants to skip PERM and self-petition if their work is in the national interest of the US. You must show: (1) your work has substantial merit and national importance, (2) you are well positioned to advance the proposed endeavor, and (3) waiving the job offer requirement would benefit the US. Popular among researchers, scientists, and entrepreneurs.",
		RelatedTerms: []string{"EB2", "I-140", "PERM", "Dhanasar Framework"},
		Forms:        []string{"I-140"},
		Source:       "https://www.uscis.gov/green-card/green-card-eligibility/green-card-for-employment-based-immigrants",
	},
	"eb3": {
		Term:         "EB3 (Third Preference Employment-Based)",
		Simple:       "A green card category for skilled workers, professionals, and other workers",
		Detail:       "EB3 covers skilled workers (jobs requiring 2+ years training), professionals (bachelor's degree required), and other workers (unskilled labor). Always requires PERM and employer sponsorship. India faces the longest backlog in EB3 — often 10+ years. Some Indian EB2 applicants downgrade to EB3 for strategic reasons related to priority date movement.",
		RelatedTerms: []string{"PERM", "I-140", "EB2", "Priority Date", "EB3 Downgrade"},
		Forms:        []string{"I-140", "ETA-9089"},
		Source:       "https://www.uscis.gov/green-card/green-card-eligibility/green-card-for-employment-based-immigrants",
	},
	"rfe": {
		Term:         "RFE (Request for Evidence)",
		Simple:       "A letter from USCIS asking for more documentation before they can decide on your case",
		Detail:       "A Request for Evidence (RFE) is issued by USCIS when they need additional documentation or clarification before making a decision. You typically have 87 days to respond. Failure to respond results in denial. RFEs are common for H1B, I-140, and I-485 applications. A strong RFE response with supporting evidence is critical — many people hire attorneys for this.",
		RelatedTerms: []string{"NOID", "I-797", "I-140", "I-485", "H1B"},
		Forms:        []string{"I-797"},
		Source:       "https://www.uscis.gov/forms/filing-guidance/responding-to-uscis-requests",
	},
	"noid": {
		Term:         "NOID (Notice of Intent to Deny)",
		Simple:       "A warning from USCIS that they plan to deny your case — more serious than an RFE",
		Detail:       "A Notice of Intent to Deny (NOID) is more serious than an RFE. USCIS issues a NOID when they have already made a preliminary determination to deny your case and want to give you a chance to respond. You typically have 30 days to respond. A NOID requires a very strong response and usually warrants hiring an experienced immigration attorney.",
		RelatedTerms: []string{"RFE", "I-797", "Denial", "Appeal"},
		Forms:        []string{"I-797"},
		Source:       "https://www.uscis.gov/forms/filing-guidance/responding-to-uscis-requests",
	},
	"premium processing": {
		Term:         "Premium Processing",
		Simple:       "An optional service to get a faster USCIS decision — currently costs $2,805",
		Detail:       "Premium Processing is an optional USCIS service that guarantees a decision (approval, RFE, NOID, or denial) within 15 business days for eligible petition types including H1B, L1, O1, and I-140. Filed using Form I-907. USCIS can suspend premium processing during periods of high volume. Premium processing does not guarantee approval — just a faster decision.",
		RelatedTerms: []string{"I-907", "H1B", "I-140", "L1", "O1"},
		Forms:        []string{"I-907"},
		Source:       "https://www.uscis.gov/forms/all-forms/request-for-premium-processing",
	},
	"cspa": {
		Term:         "CSPA (Child Status Protection Act)",
		Simple:       "A law that protects children from aging out of dependent status when they turn 21",
		Detail:       "The Child Status Protection Act protects children from losing their immigration benefits when they turn 21. Under CSPA, a child's age is calculated by subtracting the time the I-130 or I-140 was pending from their actual age. If the calculated age is under 21, they remain eligible as a child. However, CSPA has limitations and doesn't protect all children in all situations — consult an attorney.",
		RelatedTerms: []string{"Age Out", "I-140", "I-485", "Dependent"},
		Forms:        []string{"I-485"},
		Source:       "https://www.uscis.gov/green-card/green-card-processes-and-procedures/child-status-protection-act",
	},
	"visa bulletin": {
		Term:         "Visa Bulletin",
		Simple:       "A monthly publication by the State Department showing which priority dates can file for green cards",
		Detail:       "The Visa Bulletin is published monthly by the US Department of State. It shows the Final Action Dates and Dates for Filing for each employment-based and family-based green card category by country. When your priority date is earlier than the cutoff date in the bulletin, you can file I-485 (or it can be approved). The bulletin is released around the 8th-10th of each month for the following month.",
		RelatedTerms: []string{"Priority Date", "Final Action Date", "Date for Filing", "Retrogression"},
		Forms:        []string{"I-485"},
		Source:       "https://travel.state.gov/content/travel/en/legal/visa-law0/visa-bulletin.html",
	},
	"visa retrogression": {
		Term:         "Visa Retrogression",
		Simple:       "When priority date cutoffs move backward in the Visa Bulletin — making previously eligible applicants ineligible again",
		Detail:       "Retrogression occurs when the State Department moves priority date cutoffs backward in the Visa Bulletin due to high demand for visa numbers. This can happen to applicants who were previously eligible to file I-485 or whose cases were pending. Retrogression is most common for India EB2 and EB3 categories due to the massive backlog.",
		RelatedTerms: []string{"Visa Bulletin", "Priority Date", "Final Action Date", "India EB2"},
		Forms:        []string{},
		Source:       "https://travel.state.gov/content/travel/en/legal/visa-law0/visa-bulletin.html",
	},
	"lca": {
		Term:         "LCA (Labor Condition Application)",
		Simple:       "A Department of Labor attestation your employer files before submitting an H1B petition",
		Detail:       "The Labor Condition Application (LCA) is filed by employers with the Department of Labor before filing an H1B petition. The employer attests they will pay the prevailing wage, working conditions are similar to US workers, there is no strike or lockout, and employees have been notified. LCA approval is required before filing Form I-129 for H1B.",
		RelatedTerms: []string{"H1B", "I-129", "Prevailing Wage", "DOL"},
		Forms:        []string{"ETA-9035"},
		Source:       "https://www.dol.gov/agencies/eta/foreign-labor/programs/h-1b",
	},
	"prevailing wage": {
		Term:         "Prevailing Wage",
		Simple:       "The minimum salary an employer must pay an H1B or green card sponsored employee",
		Detail:       "The prevailing wage is the average wage paid to similarly employed workers in the same geographic area. For H1B, employers must pay at least the prevailing wage as determined by DOL. There are four wage levels (I-IV) based on experience and complexity. Underpaying H1B workers is a violation that can result in back wages and debarment from the program.",
		RelatedTerms: []string{"LCA", "H1B", "PERM", "DOL", "Wage Level"},
		Forms:        []string{"ETA-9035", "ETA-9089"},
		Source:       "https://www.dol.gov/agencies/eta/foreign-labor/programs/h-1b",
	},
	"o1": {
		Term:         "O1 Visa",
		Simple:       "A visa for individuals with extraordinary ability or achievement in their field",
		Detail:       "The O1 visa is for individuals with extraordinary ability in sciences, education, business, or athletics (O1A) or extraordinary achievement in arts, motion picture, or TV (O1B). Unlike H1B, O1 is not subject to a cap and can be renewed indefinitely. It requires employer sponsorship or an agent. O1A criteria overlap significantly with EB1A for green card purposes.",
		RelatedTerms: []string{"EB1A", "H1B", "Extraordinary Ability", "I-129"},
		Forms:        []string{"I-129"},
		Source:       "https://www.uscis.gov/working-in-the-united-states/temporary-workers/o-1-visa-individuals-with-extraordinary-ability-or-achievement",
	},
	"f1": {
		Term:         "F1 Visa",
		Simple:       "A student visa for full-time academic study at a US institution",
		Detail:       "The F1 visa is for international students enrolled full-time at an accredited US college, university, or academic institution. F1 students can work on-campus part-time and may be eligible for OPT and STEM OPT after graduation. F1 status is maintained through a valid I-20 from your school's DSO (Designated School Official).",
		RelatedTerms: []string{"OPT", "STEM OPT", "CPT", "I-20", "DSO", "SEVIS"},
		Forms:        []string{"I-20", "I-765"},
		Source:       "https://www.uscis.gov/working-in-the-united-states/students-and-exchange-visitors/students-and-employment",
	},
	"opt": {
		Term:         "OPT (Optional Practical Training)",
		Simple:       "Work authorization for F1 students to gain practical experience related to their degree",
		Detail:       "Optional Practical Training (OPT) allows F1 students to work in the US in a job directly related to their major area of study. Standard OPT provides 12 months of work authorization. STEM OPT provides an additional 24-month extension for students in STEM fields. OPT can be used before graduation (pre-completion) or after (post-completion).",
		RelatedTerms: []string{"F1", "STEM OPT", "EAD", "I-765", "Cap-Gap"},
		Forms:        []string{"I-765"},
		Source:       "https://www.uscis.gov/working-in-the-united-states/students-and-exchange-visitors/optional-practical-training-opt-for-f-1-students",
	},
	"stem opt": {
		Term:         "STEM OPT",
		Simple:       "A 24-month extension of OPT for students in STEM fields",
		Detail:       "STEM OPT extends standard 12-month OPT by 24 months for F1 students who graduated with a qualifying STEM degree (science, technology, engineering, mathematics). The employer must be enrolled in E-Verify. Total STEM OPT duration is 36 months combined with standard OPT. Many tech workers use STEM OPT while waiting for H1B cap selection.",
		RelatedTerms: []string{"OPT", "F1", "E-Verify", "H1B", "Cap-Gap"},
		Forms:        []string{"I-765"},
		Source:       "https://www.uscis.gov/working-in-the-united-states/students-and-exchange-visitors/optional-practical-training-extension-for-stem-students-stem-opt",
	},
	"green card": {
		Term:         "Green Card (Permanent Resident Card)",
		Simple:       "Official proof of your lawful permanent resident status in the United States",
		Detail:       "A Green Card (Form I-551) gives you the right to live and work permanently in the US. Most green cards are valid for 10 years and must be renewed. Conditional green cards (based on marriage less than 2 years or EB5 investment) are valid for 2 years. After 5 years as a green card holder (3 years if married to a US citizen), you may be eligible for naturalization.",
		RelatedTerms: []string{"LPR", "Adjustment of Status", "Naturalization", "I-551", "Conditional Green Card"},
		Forms:        []string{"I-485", "I-90"},
		Source:       "https://www.uscis.gov/green-card",
	},
	"i-797": {
		Term:         "Form I-797 (Notice of Action)",
		Simple:       "An official USCIS notice confirming receipt, approval, RFE, or other action on your petition",
		Detail:       "Form I-797 is used by USCIS to communicate official actions on applications and petitions. Types include: I-797C (Receipt Notice confirming USCIS received your application), I-797A (Approval Notice with I-94), I-797B (Approval Notice without I-94), and I-797E (RFE or NOID). Keep all I-797 notices — they serve as official proof of your immigration status.",
		RelatedTerms: []string{"Receipt Notice", "Approval Notice", "RFE", "NOID", "I-94"},
		Forms:        []string{"I-797"},
		Source:       "https://www.uscis.gov/i-797",
	},
	"i-94": {
		Term:         "Form I-94 (Arrival/Departure Record)",
		Simple:       "Your official record of entry into the US — shows your authorized period of stay",
		Detail:       "Form I-94 is issued by CBP when you enter the US. It shows your admission class (visa type), entry date, and authorized period of stay. Since 2013, I-94 is electronic and can be accessed at i94.cbp.dhs.gov. Your I-94 expiration date (not your visa stamp expiration) determines how long you can stay in the US. Always check your I-94 after each entry.",
		RelatedTerms: []string{"CBP", "Authorized Stay", "Overstay", "Visa Stamp"},
		Forms:        []string{"I-94"},
		Source:       "https://i94.cbp.dhs.gov",
	},
	"240-day rule": {
		Term:         "240-Day Rule",
		Simple:       "Allows H1B workers to continue working for 240 days after their status expires if an extension is pending",
		Detail:       "Under the 240-day rule, if an H1B extension petition is filed before the current H1B expires, the worker can continue working for the same employer for up to 240 days while USCIS processes the extension. This rule only applies to extensions — not new H1B petitions or employer changes. The worker must stop working if the extension is denied.",
		RelatedTerms: []string{"H1B", "I-129", "Cap-Gap", "Out of Status"},
		Forms:        []string{"I-129"},
		Source:       "https://www.uscis.gov/working-in-the-united-states/h-1b-specialty-occupations",
	},
	"specialty occupation": {
		Term:         "Specialty Occupation",
		Simple:       "A job that requires at least a bachelor's degree in a specific field — required for H1B eligibility",
		Detail:       "A specialty occupation is defined as a position that requires theoretical and practical application of highly specialized knowledge, and a bachelor's or higher degree in the specific specialty as a minimum qualification. Common specialty occupations include software engineering, accounting, architecture, medicine, and law. USCIS scrutinizes whether the job truly qualifies as a specialty occupation.",
		RelatedTerms: []string{"H1B", "LCA", "I-129", "Degree Requirement"},
		Forms:        []string{"I-129"},
		Source:       "https://www.uscis.gov/working-in-the-united-states/h-1b-specialty-occupations",
	},
	"naturalization": {
		Term:         "Naturalization",
		Simple:       "The process of becoming a US citizen after holding a green card for 5 years",
		Detail:       "Naturalization is the process by which a lawful permanent resident becomes a US citizen. Generally requires: 5 years as a green card holder (3 years if married to a US citizen), continuous residence, physical presence for at least 30 months of the 5 years, good moral character, English language ability, and knowledge of US civics. Filed using Form N-400.",
		RelatedTerms: []string{"Green Card", "LPR", "N-400", "Civics Test"},
		Forms:        []string{"N-400"},
		Source:       "https://www.uscis.gov/citizenship/apply-for-citizenship",
	},
}
